### ISSUE TITLE
Errors in starting docker-compose

### ISSUE THREAD

**Issue by micheldumontier** [strawberry-graphql/federation-demo#3]
I'm getting the following errors when i start with docker-compose up
...
books_1    |     field = StrawberryField(
books_1    |   File "/usr/local/lib/python3.10/site-packages/strawberry/field.py", line 56, in __init__
books_1    |     super().__init__(  # type: ignore
books_1    | TypeError: Field.__init__() missing 1 required positional argument: 'kw_only'
....
reviews_1  |     field = StrawberryField(
reviews_1  |   File "/usr/local/lib/python3.10/site-packages/strawberry/field.py", line 56, in __init__
reviews_1  |     super().__init__(  # type: ignore
reviews_1  | TypeError: Field.__init__() missing 1 required positional argument: 'kw_only'
...
gateway_1  | Polling running services is dangerous and not recommended in production. Polling should only be used against a registry. If you are polling running services, use with caution.
gateway_1  | ❌ Unable to start gateway Error: Couldn't load service definitions for "books" at http://books:8000/graphql: request to http://books:8000/graphql failed, reason: connect ECONNREFUSED 172.26.0.2:8000
gateway_1  |     at /app/node_modules/@apollo/gateway/src/loadServicesFromRemoteEndpoint.ts:73:15
gateway_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
gateway_1  |     at async Promise.all (index 0)
gateway_1  |     at async Object.getServiceDefinitionsFromRemoteEndpoint (/app/node_modules/@apollo/gateway/src/loadServicesFromRemoteEndpoint.ts:77:30)
gateway_1  |     at async ApolloGateway.updateSchema (/app/node_modules/@apollo/gateway/src/index.ts:423:20)
gateway_1  |     at async ApolloGateway.loadDynamic (/app/node_modules/@apollo/gateway/src/index.ts:403:7)
gateway_1  |     at async ApolloGateway.load (/app/node_modules/@apollo/gateway/src/index.ts:361:9)
gateway_1  | [nodemon] clean exit - waiting for changes before restart

**Comment by patrick91** [comment]
Hi @micheldumontier, sorry for the late reply, I just pushed a fix! Let me know if that works for you :)

I'll close the issue for now 😊

**Comment by n3tra1** [comment]
Hello!
I have same trouble:
```
gateway_1  |
gateway_1  | > gateway@1.0.0 dev /app
gateway_1  | > nodemon
gateway_1  |
gateway_1  | [nodemon] 2.0.12
gateway_1  | [nodemon] to restart at any time, enter `rs`
gateway_1  | [nodemon] watching path(s): *.*
gateway_1  | [nodemon] watching extensions: js,ts
gateway_1  | [nodemon] starting `ts-node --project tsconfig.json server.ts`
reviews_1  | Skipping virtualenv creation, as specified in config file.
books_1    | Skipping virtualenv creation, as specified in config file.
books_1    | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
books_1    | INFO:     Started reloader process [8] using statreload
reviews_1  | INFO:     Uvicorn running on http://0.0.0.0:8800 (Press CTRL+C to quit)
reviews_1  | INFO:     Started reloader process [7] using statreload
gateway_1  | Polling running services is dangerous and not recommended in production. Polling should only be used against a registry. If you are polling running services, use with caution.
gateway_1  | ❌ Unable to start gateway Error: Couldn't load service definitions for "books" at http://books:8000/graphql: request to http://books:8000/graphql failed, reason: connect ECONNREFUSED 172.23.0.3:8000
gateway_1  |     at /app/node_modules/@apollo/gateway/src/loadServicesFromRemoteEndpoint.ts:73:15
gateway_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
gateway_1  |     at async Promise.all (index 0)
gateway_1  |     at async Object.getServiceDefinitionsFromRemoteEndpoint (/app/node_modules/@apollo/gateway/src/loadServicesFromRemoteEndpoint.ts:77:30)
gateway_1  |     at async ApolloGateway.updateSchema (/app/node_modules/@apollo/gateway/src/index.ts:423:20)
gateway_1  |     at async ApolloGateway.loadDynamic (/app/node_modules/@apollo/gateway/src/index.ts:403:7)
gateway_1  |     at async ApolloGateway.load (/app/node_modules/@apollo/gateway/src/index.ts:361:9)
gateway_1  | [nodemon] clean exit - waiting for changes before restart
reviews_1  | INFO:     Started server process [9]
reviews_1  | INFO:     Waiting for application startup.
reviews_1  | INFO:     Application startup complete.
books_1    | INFO:     Started server process [10]
books_1    | INFO:     Waiting for application startup.
books_1    | INFO:     Application startup complete.
```

**Comment by micheldumontier** [comment]
No, i still get the error, even just if i try to start books

```
(base) michel@Rz:~/code/federation-demo$ docker-compose up books
Starting federation-demo_books_1 ... done
Attaching to federation-demo_books_1
books_1    | Skipping virtualenv creation, as specified in config file.
books_1    | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
books_1    | INFO:     Started reloader process [7] using statreload
books_1    | Process SpawnProcess-1:
books_1    | Traceback (most recent call last):
books_1    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
books_1    |     self.run()
books_1    |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
books_1    |     self._target(*self._args, **self._kwargs)
books_1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
books_1    |     target(sockets=sockets)
books_1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 49, in run
books_1    |     loop.run_until_complete(self.serve(sockets=sockets))
books_1    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
books_1    |     return future.result()
books_1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 56, in serve
books_1    |     config.load()
books_1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 308, in load
books_1    |     self.loaded_app = import_from_string(self.app)
books_1    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 20, in import_from_string
books_1    |     module = importlib.import_module(module_str)
books_1    |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
books_1    |     return _bootstrap._gcd_import(name[level:], package, level)
books_1    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
books_1    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
books_1    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
books_1    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
books_1    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
books_1    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
books_1    |   File "/usr/src/app/./app.py", line 10, in <module>
books_1    |     class Book:
books_1    |   File "/usr/local/lib/python3.10/site-packages/strawberry/object_type.py", line 146, in wrap
books_1    |     return _process_type(
books_1    |   File "/usr/local/lib/python3.10/site-packages/strawberry/object_type.py", line 100, in _process_type
books_1    |     fields = _get_fields(cls)
books_1    |   File "/usr/local/lib/python3.10/site-packages/strawberry/types/type_resolver.py", line 125, in _get_fields
books_1    |     field = StrawberryField(
books_1    |   File "/usr/local/lib/python3.10/site-packages/strawberry/field.py", line 56, in __init__
books_1    |     super().__init__(  # type: ignore
books_1    | TypeError: Field.__init__() missing 1 required positional argument: 'kw_only'
```
